name: ribolog
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - bioconductor-GenomicAlignments
  - bioconductor-qvalue
  - bioconductor-EnhancedVolcano
  - r-BiocManager
  - r-devtools
  - r-nnet
  - r-data.table
  - r-ggplot2
  - r-ggrepel
  - r-dplyr
  - r-cowplot
  - r-robustbase
  - r-nortest
  - r-matrixStats
  - r-sm
  - r-corrplot
  - r-DescTools
  - r-seqinr
  - r-rlist
  - r-gdata
  - r-nlme
  - r-fitdistrplus
